# Generated by Django 6.0.5 on 2026-05-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('complexity', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Начальный'), (2, 'Лёгкий'), (3, 'Средний'), (4, 'Продвинутый'), (5, 'Экспертный')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='краткое описание темы')),
                ('material_file', models.FileField(blank=True, null=True, upload_to='lecture_materials/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='topics.topic')),
            ],
        ),
    ]
