# Generated by Django 6.0.5 on 2026-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='complexity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Начальный'), (2, 'Лёгкий'), (3, 'Средний'), (4, 'Продвинутый'), (5, 'Экспертный')], null=True, verbose_name='сложность'),
        ),
    ]
